name: Reddit → Twitter Bot

on:
  s/chedule:
    - cron: "0 9 * * *"   # 9 AM UTC
    - cron: "0 12 * * *"  # 12 PM UTC
    - cron: "0 15 * * *"  # 3 PM UTC
    - cron: "0 18 * * *"  # 6 PM UTC
    - cron: "0 21 * * *"  # 9 PM UTC
  workflow_dispatch:      # allows manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python bot.py
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
