name: Reddit → Twitter Bot

on:
  schedule:
    - cron: '0 9 * * *'   # 09:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 15 * * *'  # 15:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC
    - cron: '0 21 * * *'  # 21:00 UTC
  workflow_dispatch:      # manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system deps + Python
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
        run: python bot.py
